// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cobnwjumxytlnppncynf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvYm53anVteHl0bG5wcG5jeW5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNTg3MzIsImV4cCI6MjA3MzYzNDczMn0.EPutaCb3rSJd0AJmFW-RO5yFFboO2h36UZfVXbur08c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});